user:
    pattern:  /
    defaults: { _controller: "BackendBundle:User:index" }
    
user_filter:
    pattern:  /clean_user_filter
    defaults: { _controller: "BackendBundle:User:cleanSearchUser" }

user_show:
    pattern:  /{userId}/show
    defaults: { _controller: "BackendBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{userId}/edit
    defaults: { _controller: "BackendBundle:User:edit" }

user_update:
    pattern:  /{userId}/update
    defaults: { _controller: "BackendBundle:User:update" }
    requirements: { _method: post|put }
    
user_password:
    pattern:  /{userId}/changepass
    defaults: { _controller: "BackendBundle:User:changePassword" }

user_delete:
    pattern:  /{userId}/delete
    defaults: { _controller: "BackendBundle:User:delete" }
    requirements: { _method: post|delete }
