#accept
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/CMS/workspace/
  to: /var/www/accept_env
  excludes:
    - app/cache/*
    - app/logs/*
    - web/bundles/*
releases:
  enabled: true
  max: 4
  symlink: cms
  directory: releases/cms_releases
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - permissionsConsole
    - prepareAcceptDeployment
    - prepareDeployment
    - symfony2/cache-warmup: {env: prod}
    - symfony2/assets-install
    - permissionsGroup
  post-release:
    - databaseBackup: {user: cms_accept, pass: AMB4m3tyAxwLCLMS, host: localhost, database: cms_accept}
  post-deploy: