#production fsb
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/CMS/workspace/
  to: /var/www
  excludes:
    - app/cache/*
    - app/logs/*
    - web/bundles/*
releases:
  enabled: true
  max: 10
  symlink: fsb
  directory: releases/cms_releases/fsb
hosts:
    - 10.10.1.13:
tasks:
  pre-deploy:
  on-deploy:
    - permissionsConsole
    - prepareFsbDeployment
    - prepareDeployment
    - symfony2/cache-warmup: {env: prod}
    - symfony2/assets-install
    - permissionsGroup
  post-release:
    - databaseBackup: {user: cms_fsb, pass: NhE8qxYnnDtPT7fJ, host: localhost, database: cms_fsb}
    post-deploy: