#test
deployment:
  user: estebanc
  from: /var/lib/jenkins/jobs/CMS/workspace/
  to: /var/www/html
  excludes:
    - app/cache/*
    - app/logs/*
    - web/bundles/*
releases:
  enabled: true
  max: 10
  symlink: cms
  directory: releases/cms_releases
hosts:
    - 10.10.1.15
tasks:
  pre-deploy:
  on-deploy:
    - permissionsConsole
    - prepareTestDeployment
    - prepareDeployment
    - symfony2/cache-warmup: {env: prod}
    - symfony2/assets-install
    - permissionsGroup
  post-release:
    - databaseBackup: {user: cms, pass: VNxf9DsbW3RmSbHW, host: localhost, database: cms}
  post-deploy: