#production voicegroup
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/CMS/workspace/
  to: /var/www
  excludes:
    - app/cache/*
    - app/logs/*
    - web/bundles/*
releases:
  enabled: true
  max: 10
  symlink: voicegroup
  directory: releases/cms_releases/voicegroup
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - permissionsConsole
    - prepareVoicegroupDeployment
    - prepareDeployment
    - symfony2/cache-warmup: {env: prod}
    - symfony2/assets-install
    - permissionsGroup
  post-release:
    - databaseBackup: {user: cms_voicegroup, pass: AADe4LhdFA5aVt3C, host: localhost, database: cms_voicegroup}
  post-deploy: