appointment:
    pattern:  /
    defaults: { _controller: "AppointmentBundle:Appointment:index" }

appointment_filter:
    pattern:  /filter/month/{month}/year/{year}
    defaults: { _controller: "AppointmentBundle:Appointment:searchAppointment"}

appointment_clean_filter:
    pattern:  /clean_filter
    defaults: { _controller: "AppointmentBundle:Appointment:cleanSearchAppointment" }

appointment_show:
    pattern:  /{id}/show
    defaults: { _controller: "AppointmentBundle:Appointment:show" }

appointment_new:
    pattern:  /new/title/{title}/
    defaults: { _controller: "AppointmentBundle:Appointment:new" }

appointment_new_date:
    pattern:  /new/hour/{hour}/minute/{minute}/day/{day}/month/{month}/year/{year}/{recruiter_id}
    defaults: { _controller: "AppointmentBundle:Appointment:newDate", recruiter_id: null }

appointment_new_automated:
    pattern:  /new/
    defaults: { _controller: "AppointmentBundle:Appointment:newDate", recruiter_id: null }

appointment_create:
    pattern:  /create
    defaults: { _controller: "AppointmentBundle:Appointment:create" }
    requirements: { _method: post }

appointment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AppointmentBundle:Appointment:edit" }

appointment_update:
    pattern:  /{id}/update
    defaults: { _controller: "AppointmentBundle:Appointment:update" }
    requirements: { _method: post|put }

appointment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AppointmentBundle:Appointment:delete" }
    requirements: { _method: post|delete }

appointment_outcome_edit:
    pattern:  /{id}/outcome_edit
    defaults: { _controller: "AppointmentBundle:Appointment:outcomeEdit" }
    
appointment_map_month:
    pattern:  /map/month/{month}/year/{year}
    defaults: { _controller: "AppointmentBundle:Appointment:map" }