backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /admin

reporting:
    resource: "@ReportingBundle/Resources/config/routing.yml"
    prefix:   /reporting

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /calendar

note:
    resource: "@NoteBundle/Resources/config/routing.yml"
    prefix:   /

rule:
    resource: "@RuleBundle/Resources/config/routing.yml"
    prefix:   /

appointment:
    resource: "@AppointmentBundle/Resources/config/routing.yml"
    prefix:   /calendar

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
index:
    path: /
    defaults: { _controller: "FrameworkBundle:Redirect:redirect", route: calendar_homepage }
    
login:
    path: /login
    defaults: { _controller: "BackendBundle:User:login" }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
#########
#REST API    
#########

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
  
AppointmentBundle_api:
    resource: "@AppointmentBundle/Controller/AppointmentRestController.php"
    type:     rest
    prefix:   /api