security:

    firewalls:
        secured_area:
            pattern:    ^/*
            anonymous:  ~
            form_login: 
                login_path:  login
                check_path:  login_check
                use_referer: true
            logout:
                path: logout
            remember_me:
                key:      fsb1234
                lifetime: 3600

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar/*, roles: [ROLE_RECRUITER, ROLE_APPOINTMENT_SETTER, ROLE_ADMINISTRATOR, ROLE_SUPER_USER] }
        - { path: ^/reporting/*, roles: [ROLE_SUPER_USER] }
        - { path: ^/backend/*, roles: [ROLE_ADMINISTRATOR] }
        # You can use a regular expression for the languges '[a-z]{2}'
    
    providers:
        users:
            entity: { class: Fsb\USerBundle\Entity\User, property: login }
    
    encoders:
        Fsb\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
    
