security:

    firewalls:
        secured_area:
            pattern:    ^/*
            anonymous:  ~
            form_login: 
                login_path:  login
                check_path:  login_check
                # use_referer: true
                default_target_path: /calendar
            logout:
                path: logout
            remember_me:
                key:      fsb1234
                lifetime: 3600

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar/month/\d*/year/\d*/., roles: [ROLE_ADMINISTRATOR] }
        - { path: ^/calendar/day/\d*/month/\d*/year/\d*/., roles: [ROLE_ADMINISTRATOR] }
        - { path: ^/calendar/diary/day/\d*/month/\d*/year/\d*/., roles: [ROLE_ADMINISTRATOR] }
        - { path: ^/calendar/unavailabledate/searchAvailability/*, roles: [ROLE_ADMINISTRATOR, ROLE_APPOINTMENT_SETTER] }
        - { path: ^/calendar/rule/all, roles: [ROLE_APPOINTMENT_SETTER, ROLE_ADMINISTRATOR] }
        - { path: ^/calendar/rule/new, roles: [ROLE_APPOINTMENT_SETTER, ROLE_ADMINISTRATOR] }
        - { path: ^/calendar/rule/\d*/*, roles: [ROLE_RECRUITER, ROLE_APPOINTMENT_SETTER, ROLE_ADMINISTRATOR] }
        - { path: ^/calendar/*, roles: [ROLE_RECRUITER, ROLE_APPOINTMENT_SETTER, ROLE_ADMINISTRATOR, ROLE_SUPER_USER] }
        - { path: ^/reporting/*, roles: [ROLE_SUPER_USER, ROLE_ADMINISTRATOR] }
        - { path: ^/backend/*, roles: [ROLE_ADMINISTRATOR] }
        # You can use a regular expression for the languges '[a-z]{2}'
    
    providers:
        users:
            entity: { class: Fsb\UserBundle\Entity\User, property: login }
    
    encoders:
        Fsb\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
    
