unavailableDate:
    pattern:  /
    defaults: { _controller: "RuleBundle:UnavailableDate:index" }

unavailableDate_search_availability:
    pattern:  searchAvailability/month/{month}/year/{year}
    defaults: { _controller: "RuleBundle:UnavailableDate:searchAvailability"}

unavailabledate_clean_availability_filter:
    pattern:  /clean_availability_filter
    defaults: { _controller: "RuleBundle:UnavailableDate:cleanSearchAvailability" }

unavailableDate_show:
    pattern:  /{unavailableDateId}/show
    defaults: { _controller: "RuleBundle:UnavailableDate:show" }

unavailableDate_new:
    pattern:  /new
    defaults: { _controller: "RuleBundle:UnavailableDate:new" }
    
unavailableDate_new_date:
    pattern:  /new/hour/{hour}/minute/{minute}/day/{day}/month/{month}/year/{year}/{recruiter_id}
    defaults: { _controller: "RuleBundle:UnavailableDate:newDate", recruiter_id: null }

unavailableDate_create:
    pattern:  /create
    defaults: { _controller: "RuleBundle:UnavailableDate:create" }
    requirements: { _method: post }

unavailableDate_edit:
    pattern:  /{unavailableDateId}/edit/{recruiter_id}
    defaults: { _controller: "RuleBundle:UnavailableDate:edit", recruiter_id: null }

unavailableDate_update:
    pattern:  /{unavailableDateId}/update
    defaults: { _controller: "RuleBundle:UnavailableDate:update" }
    requirements: { _method: post|put }

unavailableDate_delete:
    pattern:  /{unavailableDateId}/delete
    defaults: { _controller: "RuleBundle:UnavailableDate:delete" }
    requirements: { _method: post|delete }
