calendar_homepage:
    pattern:  /
    defaults: { _controller: "CalendarBundle:Default:index" }

calendar_month:
    pattern:  /month/{month}/year/{year}
    defaults: { _controller: "CalendarBundle:Default:month" }

calendar_day:
    pattern:  /day/{day}/month/{month}/year/{year}
    defaults: { _controller: "CalendarBundle:Default:day" }
    
calendar_diary:
    pattern:  /diary/day/{day}/month/{month}/year/{year}
    defaults: { _controller: "CalendarBundle:Default:diary" }