parameters:
#    reporting.example.class: Fsb\ReportingBundle\Example

services:
#    reporting.example:
#        class: %reporting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
