note_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: "NoteBundle:Default:index" }

NoteBundle_note:
     resource: "@NoteBundle/Resources/config/routing/note.yml"
     prefix:   /calendar/note