<?php

namespace Fsb\RuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnavailableDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnavailableDateRepository extends EntityRepository
{
	
	/**
	 * Get The abank holidays
	 *
	 * @return array UnavailableDate
	 * 
	 */
	public function findBankHolidays(){
	
		$em = $this->getEntityManager();
	
		$dql = 'SELECT ud.unavailableDate
					FROM RuleBundle:UnavailableDate ud
					JOIN ud.reason udr
					WHERE
						udr.reason = :reason
					ORDER BY ud.unavailableDate ASC';
	
		$query = $em->createQuery($dql);
		$query->setParameter('reason', "Bank Holiday");
	
		$bankHolidays = $query->getResult();
	
		return $bankHolidays;
	}
}
