<?php

namespace Fsb\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 * Get All the users by a role
	 *
	 * @param Role $role Get the Users  by a role
	 *
	 * @return array Departments
	 */
	public function findUsersByRole($role){
	
		$em = $this->getEntityManager();
	
		$dql = 'SELECT u, ur
					FROM UserBundle:User u
					JOIN u.role ur
					WHERE ur.name = :role
					ORDER BY ur.name ASC';
	
		$query = $em->createQuery($dql);
		$query->setParameter('role', $role);
	
		$user_ar = $query->getResult();
	
		return $user_ar;
	}
}
