parameters:
#    appointment.example.class: Fsb\AppointmentBundle\Example

services:
#    appointment.example:
#        class: %appointment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
