backend_homepage:
    path: /
    defaults: { _controller: "BackendBundle:Default:index" }

BackendBundle_user:
     resource: "@BackendBundle/Resources/config/routing/user.yml"
     prefix:   /user

     
backend_automated_control:
    path: /automated
    defaults: { _controller: "BackendBundle:Default:automatedControl" }